/** @format */

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_EXIT = "ADD_PRODUCT_EXIT";
export const SAVE_PRODUCT_ERROR = "SAVE_PRODUCT_ERROR";

export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const LOADING_PRODUCTS_EXIT = "LOADING_PRODUCTS_EXIT";
export const LOADING_PRODUCTS_ERROR = "LOADING_PRODUCTS_ERROR";

export const GET_PRODUCT_REMOVE = "GET_PRODUCT_REMOVE";
export const GET_PRODUCT_EXIT = "GET_PRODUCT_EXIT";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
export const START_EDITING_PRODUCT = "START_EDITING_PRODUCT";
export const GET_PRODUCT_EDIT_EXIT = "GET_PRODUCT_EDIT_EXIT";
export const GET_PRODUCT_EDIT_ERROR = "GET_PRODUCT_EDIT_EXIT";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
